//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetWPF.SocialNetServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/SocialNetDAL")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SocialNetWPF.SocialNetServiceReference.Event> EventsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Collections.Generic.List<SocialNetWPF.SocialNetServiceReference.Event> Events {
            get {
                return this.EventsField;
            }
            set {
                if ((object.ReferenceEquals(this.EventsField, value) != true)) {
                    this.EventsField = value;
                    this.RaisePropertyChanged("Events");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://schemas.datacontract.org/2004/07/SocialNetDAL")]
    [System.SerializableAttribute()]
    public partial class Event : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategorieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateDebutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Categorie {
            get {
                return this.CategorieField;
            }
            set {
                if ((object.ReferenceEquals(this.CategorieField, value) != true)) {
                    this.CategorieField = value;
                    this.RaisePropertyChanged("Categorie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime DateDebut {
            get {
                return this.DateDebutField;
            }
            set {
                if ((this.DateDebutField.Equals(value) != true)) {
                    this.DateDebutField = value;
                    this.RaisePropertyChanged("DateDebut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime DateFin {
            get {
                return this.DateFinField;
            }
            set {
                if ((this.DateFinField.Equals(value) != true)) {
                    this.DateFinField = value;
                    this.RaisePropertyChanged("DateFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Statut {
            get {
                return this.StatutField;
            }
            set {
                if ((object.ReferenceEquals(this.StatutField, value) != true)) {
                    this.StatutField = value;
                    this.RaisePropertyChanged("Statut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/SocialNetDAL")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PseudoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvatarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SocialNetWPF.SocialNetServiceReference.Event> EventsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pseudo {
            get {
                return this.PseudoField;
            }
            set {
                if ((object.ReferenceEquals(this.PseudoField, value) != true)) {
                    this.PseudoField = value;
                    this.RaisePropertyChanged("Pseudo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Avatar {
            get {
                return this.AvatarField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarField, value) != true)) {
                    this.AvatarField = value;
                    this.RaisePropertyChanged("Avatar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public System.Collections.Generic.List<SocialNetWPF.SocialNetServiceReference.Event> Events {
            get {
                return this.EventsField;
            }
            set {
                if ((object.ReferenceEquals(this.EventsField, value) != true)) {
                    this.EventsField = value;
                    this.RaisePropertyChanged("Events");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SocialNetServiceReference.ISocialNetService")]
    public interface ISocialNetService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialNetService/AddCategories", ReplyAction="http://tempuri.org/ISocialNetService/AddCategoriesResponse")]
        bool AddCategories(string nom, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialNetService/UpdateCategories", ReplyAction="http://tempuri.org/ISocialNetService/UpdateCategoriesResponse")]
        bool UpdateCategories(string oldNom, string nom, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialNetService/DeleteCategories", ReplyAction="http://tempuri.org/ISocialNetService/DeleteCategoriesResponse")]
        bool DeleteCategories(string nom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialNetService/GetCategories", ReplyAction="http://tempuri.org/ISocialNetService/GetCategoriesResponse")]
        SocialNetWPF.SocialNetServiceReference.Category GetCategories(string nom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialNetService/ListCategories", ReplyAction="http://tempuri.org/ISocialNetService/ListCategoriesResponse")]
        System.Collections.Generic.List<SocialNetWPF.SocialNetServiceReference.Category> ListCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialNetService/AddEvents", ReplyAction="http://tempuri.org/ISocialNetService/AddEventsResponse")]
        bool AddEvents(string nom, string categorie, System.DateTime dateDebut, System.DateTime dateFin, string description, string photo, string statut, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialNetService/UpdateEvents", ReplyAction="http://tempuri.org/ISocialNetService/UpdateEventsResponse")]
        bool UpdateEvents(string oldNom, string nom, string categorie, System.DateTime dateDebut, System.DateTime dateFin, string description, string photo, string statut, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialNetService/DeleteEvents", ReplyAction="http://tempuri.org/ISocialNetService/DeleteEventsResponse")]
        bool DeleteEvents(string nom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialNetService/GetEvents", ReplyAction="http://tempuri.org/ISocialNetService/GetEventsResponse")]
        SocialNetWPF.SocialNetServiceReference.Event GetEvents(string nom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialNetService/ListEvents", ReplyAction="http://tempuri.org/ISocialNetService/ListEventsResponse")]
        System.Collections.Generic.List<SocialNetWPF.SocialNetServiceReference.Event> ListEvents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialNetService/AddUsers", ReplyAction="http://tempuri.org/ISocialNetService/AddUsersResponse")]
        bool AddUsers(string pseudo, string nom, string prenom, string password, string avatar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialNetService/UpdateUsers", ReplyAction="http://tempuri.org/ISocialNetService/UpdateUsersResponse")]
        bool UpdateUsers(string oldPseudo, string pseudo, string nom, string prenom, string password, string avatar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialNetService/DeleteUsers", ReplyAction="http://tempuri.org/ISocialNetService/DeleteUsersResponse")]
        bool DeleteUsers(string pseudo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialNetService/GetUsers", ReplyAction="http://tempuri.org/ISocialNetService/GetUsersResponse")]
        SocialNetWPF.SocialNetServiceReference.User GetUsers(string nom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialNetService/ListUsers", ReplyAction="http://tempuri.org/ISocialNetService/ListUsersResponse")]
        System.Collections.Generic.List<SocialNetWPF.SocialNetServiceReference.User> ListUsers();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISocialNetServiceChannel : SocialNetWPF.SocialNetServiceReference.ISocialNetService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SocialNetServiceClient : System.ServiceModel.ClientBase<SocialNetWPF.SocialNetServiceReference.ISocialNetService>, SocialNetWPF.SocialNetServiceReference.ISocialNetService {
        
        public SocialNetServiceClient() {
        }
        
        public SocialNetServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SocialNetServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocialNetServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocialNetServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddCategories(string nom, string description) {
            return base.Channel.AddCategories(nom, description);
        }
        
        public bool UpdateCategories(string oldNom, string nom, string description) {
            return base.Channel.UpdateCategories(oldNom, nom, description);
        }
        
        public bool DeleteCategories(string nom) {
            return base.Channel.DeleteCategories(nom);
        }
        
        public SocialNetWPF.SocialNetServiceReference.Category GetCategories(string nom) {
            return base.Channel.GetCategories(nom);
        }
        
        public System.Collections.Generic.List<SocialNetWPF.SocialNetServiceReference.Category> ListCategories() {
            return base.Channel.ListCategories();
        }
        
        public bool AddEvents(string nom, string categorie, System.DateTime dateDebut, System.DateTime dateFin, string description, string photo, string statut, string user) {
            return base.Channel.AddEvents(nom, categorie, dateDebut, dateFin, description, photo, statut, user);
        }
        
        public bool UpdateEvents(string oldNom, string nom, string categorie, System.DateTime dateDebut, System.DateTime dateFin, string description, string photo, string statut, string user) {
            return base.Channel.UpdateEvents(oldNom, nom, categorie, dateDebut, dateFin, description, photo, statut, user);
        }
        
        public bool DeleteEvents(string nom) {
            return base.Channel.DeleteEvents(nom);
        }
        
        public SocialNetWPF.SocialNetServiceReference.Event GetEvents(string nom) {
            return base.Channel.GetEvents(nom);
        }
        
        public System.Collections.Generic.List<SocialNetWPF.SocialNetServiceReference.Event> ListEvents() {
            return base.Channel.ListEvents();
        }
        
        public bool AddUsers(string pseudo, string nom, string prenom, string password, string avatar) {
            return base.Channel.AddUsers(pseudo, nom, prenom, password, avatar);
        }
        
        public bool UpdateUsers(string oldPseudo, string pseudo, string nom, string prenom, string password, string avatar) {
            return base.Channel.UpdateUsers(oldPseudo, pseudo, nom, prenom, password, avatar);
        }
        
        public bool DeleteUsers(string pseudo) {
            return base.Channel.DeleteUsers(pseudo);
        }
        
        public SocialNetWPF.SocialNetServiceReference.User GetUsers(string nom) {
            return base.Channel.GetUsers(nom);
        }
        
        public System.Collections.Generic.List<SocialNetWPF.SocialNetServiceReference.User> ListUsers() {
            return base.Channel.ListUsers();
        }
    }
}
